'use client'

import { useEffect, useMemo, useState } from 'react'
import { Activity, Gauge, TrendingUp } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { cn } from '@/lib/utils'
import { useCrowdShield } from '@/lib/crowdshield/context'
import { ZONES } from '@/lib/crowdshield/zones'
import { getRiskColor, RISK_BADGE_CLASSES } from '@/lib/crowdshield/theme'
import type { RiskLevel } from '@/lib/crowdshield/types'

export function AnalyticsSection() {
  const { events, history, totalEvents, interventions } = useCrowdShield()
  const [isLoaded, setIsLoaded] = useState(false)
  useEffect(() => { const timer = setTimeout(() => setIsLoaded(true), 300); return () => clearTimeout(timer) }, [])
  const barData = useMemo(() => ZONES.map(zone => { const event = events.get(zone.id); return { name: zone.name.split(' ')[0], fullName: zone.name, risk_score: event?.risk_score ?? 0, color: getRiskColor(event?.risk_level) } }), [events])
  const trendData = useMemo(() => { const length = Math.min(20, Math.max(...ZONES.map(zone => history.get(zone.id)?.length ?? 0), 0)); return Array.from({ length }, (_, index) => Object.fromEntries([['tick', index + 1], ...ZONES.map(zone => { const points = history.get(zone.id) ?? []; const point = points[points.length - length + index]; return [zone.id, point?.risk_score ?? null] })])) }, [history])
  const avgRisk = events.size ? Array.from(events.values()).reduce((sum, event) => sum + event.risk_score, 0) / events.size : 0
  const critical = Array.from(events.values()).filter(event => event.risk_level === 'critical').length
  return <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{[{ label: 'Avg Risk Score', value: avgRisk ? avgRisk.toFixed(2) : '—', sub: 'across monitored zones', icon: Activity }, { label: 'Total Events', value: totalEvents, sub: 'telemetry frames processed', icon: TrendingUp }, { label: 'Interventions', value: interventions.filter(item => item.state !== 'idle').length, sub: `${critical} critical zones active`, icon: Gauge }].map(item => <div key={item.label} className="bg-card border border-border rounded-xl p-5 flex items-center gap-4"><div className="w-12 h-12 rounded-xl flex items-center justify-center bg-secondary"><item.icon className="w-5 h-5 text-accent" /></div><div><p className="text-xs text-muted-foreground font-semibold uppercase tracking-wider">{item.label}</p><p className="text-2xl font-bold text-foreground">{item.value}</p><p className="text-xs text-muted-foreground">{item.sub}</p></div></div>)}</div>
    <div className="bg-card border border-border rounded-xl p-5"><h3 className="text-base font-semibold text-foreground">Zone Risk Scores</h3><p className="text-sm text-muted-foreground mb-5">Live density comparison · threshold at <span className="text-destructive font-mono font-bold">0.70</span></p><div className={cn('h-[260px] transition-opacity duration-700', isLoaded ? 'opacity-100' : 'opacity-0')}><ResponsiveContainer width="100%" height="100%"><BarChart data={barData}><CartesianGrid strokeDasharray="3 3" stroke="oklch(0.22 0.005 260)" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: 'oklch(0.65 0 0)', fontSize: 12 }}/><YAxis domain={[0, 1]} axisLine={false} tickLine={false} tickFormatter={value => value.toFixed(1)}/><Tooltip/><ReferenceLine y={0.7} stroke="#ef4444" strokeDasharray="4 4"/><Bar dataKey="risk_score" radius={[4, 4, 0, 0]}>{barData.map(item => <Cell key={item.fullName} fill={item.color}/>)}</Bar></BarChart></ResponsiveContainer></div></div>
    <div className="bg-card border border-border rounded-xl p-5"><h3 className="text-base font-semibold text-foreground">Risk Score Timeline</h3><p className="text-sm text-muted-foreground mb-5">Per-zone trend over recent telemetry frames</p><div className="h-[260px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={trendData}><CartesianGrid strokeDasharray="3 3" stroke="oklch(0.22 0.005 260)" vertical={false}/><XAxis dataKey="tick"/><YAxis domain={[0, 1]}/><Tooltip/><ReferenceLine y={0.7} stroke="#ef4444" strokeDasharray="4 4"/>{ZONES.map((zone, index) => <Line key={zone.id} dataKey={zone.id} name={zone.name} stroke={['#00b8c8', '#19c37d', '#ffc107', '#ff7a00', '#e53935'][index]} dot={false}/>)}</LineChart></ResponsiveContainer></div></div>
    <div className="bg-card border border-border rounded-xl p-5"><h3 className="text-base font-semibold text-foreground mb-4">Zone Performance Summary</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{ZONES.map(zone => { const event = events.get(zone.id); const level = (event?.risk_level ?? 'low') as RiskLevel; return <div key={zone.id} className="bg-secondary/30 border border-border rounded-xl p-4"><p className="text-sm font-semibold text-foreground">{zone.name}</p><p className="text-xs text-muted-foreground font-mono">{zone.id}</p><div className="flex justify-between mt-4 text-xs"><span className="text-muted-foreground">Risk Score</span><span className="font-mono font-bold">{event ? `${Math.round(event.risk_score * 100)}%` : '—'}</span></div><div className="h-1.5 bg-secondary rounded-full overflow-hidden mt-1"><div className="h-full bg-accent rounded-full" style={{ width: `${(event?.risk_score ?? 0) * 100}%` }}/></div><span className={cn('inline-flex mt-3 px-2 py-0.5 rounded text-[10px] font-bold uppercase', RISK_BADGE_CLASSES[level])}>{level}</span></div> })}</div></div>
  </div>
}
